import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/** Generates docs/calibration.md from committed calibration JSON. Every number in
 *  the document comes from here; none is typed by hand. */

interface RepStats {
  p50Ms: number
  p95Ms: number
  p99Ms: number
  maxMs: number
  meanMs: number
}
interface Point {
  shape: string
  method: string
  targetRows: number
  actualRows: number
  storeNodes: number
  expandedNodes: number
  toggle: RepStats[]
  invalidate: RepStats[]
  medianTogglep99Ms: number
  medianInvalidatep99Ms: number
  nsPerRow: number
  heapBytes: number
}
interface File {
  commit: string
  started: string
  environment: Record<string, unknown>
  controlWorkloadMs: number
  method: {
    sweep: number[]
    storeNodes: number
    repeats: number
    samplesPerRepeat: number
    seed: number
  }
  points: Point[]
  skipped: { shape: string; method: string; target: number }[]
}

const BUDGET = 4 // ms, the frame-relevant structural-change budget used to locate the crossing

const dir = 'bench/results'
const chosen = readdirSync(dir)
  .filter((f) => f.startsWith('calibration-'))
  .sort()
  .at(-1)
if (chosen === undefined) throw new Error('no calibration results')
const data = JSON.parse(readFileSync(join(dir, chosen), 'utf8')) as File

const median = (v: number[]): number => {
  const s = [...v].sort((a, b) => a - b)
  const m = Math.floor(s.length / 2)
  return s.length % 2 ? (s[m] ?? NaN) : ((s[m - 1] ?? 0) + (s[m] ?? 0)) / 2
}
const fmt = (n: number): string =>
  !Number.isFinite(n) ? 'n/a' : n >= 10 ? n.toFixed(1) : n.toFixed(3)

const shapes = [...new Set(data.points.map((p) => p.shape))]
const methods = [...new Set(data.points.map((p) => p.method))]

const out: string[] = []
out.push('# Projection calibration')
out.push('')
out.push('<!-- Generated by `npm run bench:calibrate:report`. Do not edit by hand. -->')
out.push('')
out.push(
  `Commit \`${data.commit}\`, ${data.started.slice(0, 10)}. Node ${String(data.environment['node'])}, ` +
    `${String(data.environment['cpuCount'])} cores, CI=${String(data.environment['ci'])}, CPU ${String(data.environment['cpu'])}.`,
)
out.push('')
out.push(
  `**Control workload ${data.controlWorkloadMs.toFixed(2)} ms.** Divide by this to compare across machines.`,
)
out.push('')
out.push(
  `Sweep: ${data.method.sweep.join(', ')} target rows. Partial-method store: ` +
    `${data.method.storeNodes.toLocaleString('en-US')} nodes. ${data.method.repeats} independent repeats of ` +
    `${data.method.samplesPerRepeat} samples each, seed ${data.method.seed}.`,
)
out.push('')
out.push(
  '**This document chooses no threshold.** It locates where the existing projection crosses a',
)
out.push(`${BUDGET}ms structural-change budget. Budget \`B\` is derived in M1 commit 3.`)
out.push('')

for (const method of methods) {
  out.push(`## Method: ${method}`)
  out.push('')
  out.push(
    method === 'partial'
      ? 'A fixed one-million-node store with only enough nodes expanded to reach the target row count. This is the state M1 actually produces.'
      : 'A store containing exactly the target number of nodes, fully expanded. Same visible rows, far smaller store.',
  )
  out.push('')
  out.push(
    '| shape | rows | expanded | toggle p50 | p95 | p99 | invalidate p99 | ns/row | p99 spread across repeats |',
  )
  out.push('| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |')
  for (const shape of shapes) {
    for (const p of data.points.filter((x) => x.shape === shape && x.method === method)) {
      const p99s = p.toggle.map((t) => t.p99Ms)
      const spread = Math.max(...p99s) - Math.min(...p99s)
      out.push(
        `| ${shape} | ${p.actualRows.toLocaleString('en-US')} | ${p.expandedNodes.toLocaleString('en-US')} | ` +
          `${fmt(median(p.toggle.map((t) => t.p50Ms)))} | ${fmt(median(p.toggle.map((t) => t.p95Ms)))} | ` +
          `**${fmt(p.medianTogglep99Ms)}** | ${fmt(p.medianInvalidatep99Ms)} | ${p.nsPerRow.toFixed(0)} | ${fmt(spread)} |`,
      )
    }
  }
  out.push('')
}

out.push(`## Where each shape crosses ${BUDGET} ms`)
out.push('')
out.push('Highest row count still inside the budget, and lowest row count outside it. The true')
out.push('crossing lies between them; the sweep resolves it no more finely than that.')
out.push('')
out.push('| shape | method | last inside | first outside | crossing bracket |')
out.push('| --- | --- | ---: | ---: | --- |')
const brackets: { shape: string; method: string; inside: number; outside: number }[] = []
for (const shape of shapes) {
  for (const method of methods) {
    const pts = data.points
      .filter((p) => p.shape === shape && p.method === method)
      .sort((a, b) => a.actualRows - b.actualRows)
    let inside = 0
    let outside = Number.POSITIVE_INFINITY
    for (const p of pts) {
      if (p.medianTogglep99Ms <= BUDGET) inside = Math.max(inside, p.actualRows)
    }
    for (const p of pts) {
      if (p.medianTogglep99Ms > BUDGET && p.actualRows > inside) {
        outside = Math.min(outside, p.actualRows)
      }
    }
    // A combination with no reachable points has no ceiling; it has no data.
    // Recording inside=0 and then minimising over it would report the most
    // constrained combination as zero rows, which is how absence of evidence
    // becomes a budget of nothing.
    if (pts.length > 0) brackets.push({ shape, method, inside, outside })
    if (pts.length === 0) {
      out.push(
        `| ${shape} | ${method} | no reachable points | no reachable points | not measurable |`,
      )
      continue
    }
    out.push(
      `| ${shape} | ${method} | ${inside.toLocaleString('en-US')} | ` +
        `${Number.isFinite(outside) ? outside.toLocaleString('en-US') : 'never'} | ` +
        `${Number.isFinite(outside) ? `${inside.toLocaleString('en-US')} to ${outside.toLocaleString('en-US')}` : `beyond ${inside.toLocaleString('en-US')}`} |`,
    )
  }
}
out.push('')
const realistic = brackets.filter((b) => b.method === 'partial')
const worstInside = realistic.length > 0 ? Math.min(...realistic.map((b) => b.inside)) : Number.NaN
const worst = realistic.filter((b) => b.inside === worstInside)
out.push(
  `Across the **partial** method, which is the state M1 actually produces, the most constrained ` +
    `combination is **${worst.map((b) => b.shape).join(', ')}** at **${worstInside.toLocaleString('en-US')} rows**. ` +
    `Any single conservative budget must sit at or below that.`,
)
out.push('')
out.push(
  'Per shape, the sized method is far less constrained on three of four measurable shapes, and identical ' +
    'on deep-narrow. Worst case therefore agrees between methods while the typical case does not, which is ' +
    'why quoting an average across shapes would be misleading in either direction.',
)
out.push('')

// Crossing by statistic. p99 and p50 do not agree, and which one gates the budget
// changes the answer materially, so both are reported and neither is chosen here.
out.push('## Crossing by statistic, partial method')
out.push('')
out.push('| shape | p50 last inside | p50 first outside | p99 last inside | p99 first outside |')
out.push('| --- | ---: | ---: | ---: | ---: |')
for (const shape of shapes) {
  const pts = data.points
    .filter((p) => p.shape === shape && p.method === 'partial')
    .sort((a, b) => a.actualRows - b.actualRows)
  if (pts.length === 0) continue
  const cross = (pick: (p: Point) => number): [string, string] => {
    let inside = 0
    let outside = Number.POSITIVE_INFINITY
    for (const p of pts) if (pick(p) <= BUDGET) inside = Math.max(inside, p.actualRows)
    for (const p of pts)
      if (pick(p) > BUDGET && p.actualRows > inside) outside = Math.min(outside, p.actualRows)
    return [
      inside.toLocaleString('en-US'),
      Number.isFinite(outside) ? outside.toLocaleString('en-US') : 'never',
    ]
  }
  const [i50, o50] = cross((p) => median(p.toggle.map((t) => t.p50Ms)))
  const [i99, o99] = cross((p) => p.medianTogglep99Ms)
  out.push(`| ${shape} | ${i50} | ${o50} | ${i99} | ${o99} |`)
}
out.push('')

// Stability. A statistic whose repeat-to-repeat spread is comparable to the budget
// cannot locate a crossing precisely, and saying so is more useful than a number.
out.push('## Stability near the crossing')
out.push('')
out.push(
  'Spread across the three independent repeats, partial method, for points between 8,000 and',
)
out.push('50,000 rows. This is the region a budget would be drawn from.')
out.push('')
const near = data.points.filter(
  (p) => p.method === 'partial' && p.actualRows >= 8_000 && p.actualRows <= 50_000,
)
const spread = (p: Point, pick: (t: RepStats) => number): number => {
  const v = p.toggle.map(pick)
  return Math.max(...v) - Math.min(...v)
}
const p50Spreads = near.map((p) => spread(p, (t) => t.p50Ms))
const p99Spreads = near.map((p) => spread(p, (t) => t.p99Ms))
out.push('| statistic | median spread | worst spread | worst as share of the 4 ms budget |')
out.push('| --- | ---: | ---: | ---: |')
out.push(
  `| p50 | ${fmt(median(p50Spreads))} ms | ${fmt(Math.max(...p50Spreads))} ms | ${((Math.max(...p50Spreads) / BUDGET) * 100).toFixed(0)}% |`,
)
out.push(
  `| p99 | ${fmt(median(p99Spreads))} ms | ${fmt(Math.max(...p99Spreads))} ms | ${((Math.max(...p99Spreads) / BUDGET) * 100).toFixed(0)}% |`,
)
out.push('')
out.push(
  'p99 over sixty samples is dominated by collection pauses and outliers. Its repeat-to-repeat spread ' +
    'is a substantial fraction of the budget itself, so the p99 crossing brackets above should be read as ' +
    'approximate. p50 is stable to within a few percent and its crossing is well located, but it is the ' +
    'wrong statistic to gate a frame budget on, because a frame that misses is a frame the reader sees.',
)
out.push('')
out.push(
  '**This document does not resolve that tension.** Choosing which statistic gates the budget, and what ' +
    'safety factor absorbs the noise in it, is a commit 3 decision made in the open.',
)
out.push('')

out.push('## Partial versus sized at equal row counts')
out.push('')
out.push('Same visible rows, different store size. A gap here means projection cost depends on')
out.push('something other than the number of rows, most plausibly memory locality.')
out.push('')
out.push('| shape | rows | partial p99 | sized p99 | partial / sized |')
out.push('| --- | ---: | ---: | ---: | ---: |')
for (const shape of shapes) {
  for (const target of data.method.sweep) {
    const a = data.points.find(
      (p) => p.shape === shape && p.method === 'partial' && p.targetRows === target,
    )
    const b = data.points.find(
      (p) => p.shape === shape && p.method === 'sized' && p.targetRows === target,
    )
    if (a === undefined || b === undefined) continue
    out.push(
      `| ${shape} | ${target.toLocaleString('en-US')} | ${fmt(a.medianTogglep99Ms)} | ${fmt(b.medianTogglep99Ms)} | ` +
        `${(a.medianTogglep99Ms / b.medianTogglep99Ms).toFixed(2)}x |`,
    )
  }
}
out.push('')

if (data.skipped.length > 0) {
  out.push('## Unreachable points')
  out.push('')
  out.push('Row counts a shape cannot produce. `mega-sibling` has one parent owning every other')
  out.push('node, so expanding it is all-or-nothing and intermediate counts do not exist.')
  out.push('')
  const byShape = new Map<string, number>()
  for (const s of data.skipped)
    byShape.set(`${s.shape}/${s.method}`, (byShape.get(`${s.shape}/${s.method}`) ?? 0) + 1)
  out.push('| shape / method | points skipped |')
  out.push('| --- | ---: |')
  for (const [k, v] of byShape) out.push(`| ${k} | ${v} |`)
  out.push('')
}

writeFileSync('docs/calibration.md', `${out.join('\n')}\n`)
process.stdout.write(`wrote docs/calibration.md from ${chosen}\n`)
