import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Generates docs/benchmarks.md from committed result files.
 *
 * Every number in the documentation comes from here. Nothing is typed into prose
 * by hand, so a stale figure is impossible rather than merely discouraged.
 */
interface Measurement {
  shape: string
  nodes: number
  scenario: string
  samples: number
  batch: number
  meanMs: number
  p50Ms: number
  p95Ms: number
  p99Ms: number
  maxMs: number
  perOpP99Us: number
}
interface HeapMeasurement {
  shape: string
  nodes: number
  storeBytes: number
  projectionBytes: number
  ratio: number
  rows: number
}
interface ResultFile {
  implementation: string
  commit: string
  started: string
  environment: Record<string, unknown>
  controlWorkloadMs: number
  unloadedFraction: number
  measurements: Measurement[]
  heaps: HeapMeasurement[]
}

const RESULTS = 'bench/results'
const files = readdirSync(RESULTS)
  .filter((f) => f.startsWith('materialized-') && f.endsWith('.json'))
  .sort()
const chosen = files.at(-1)
if (chosen === undefined) throw new Error('no results to report on')
const data = JSON.parse(readFileSync(join(RESULTS, chosen), 'utf8')) as ResultFile

const shapes = [...new Set(data.measurements.map((m) => m.shape))]
const sizes = [...new Set(data.measurements.map((m) => m.nodes))].sort((a, b) => a - b)
const scenarios = [...new Set(data.measurements.map((m) => m.scenario))]

const fmt = (n: number): string =>
  !Number.isFinite(n) ? 'n/a' : n >= 100 ? n.toFixed(0) : n >= 1 ? n.toFixed(2) : n.toFixed(3)
const bytes = (n: number): string =>
  n >= 1e9
    ? `${(n / 1e9).toFixed(2)} GB`
    : n >= 1e6
      ? `${(n / 1e6).toFixed(1)} MB`
      : `${(n / 1e3).toFixed(0)} kB`

const out: string[] = []
out.push('# Benchmarks')
out.push('')
out.push('<!-- Generated by `npm run bench:report`. Do not edit by hand. -->')
out.push('')
out.push(
  `Implementation: **${data.implementation}** at commit \`${data.commit}\`, run ${data.started.slice(0, 10)}.`,
)
out.push('')
out.push(
  `Environment: Node ${String(data.environment['node'])}, ${String(data.environment['platform'])}, ` +
    `${String(data.environment['cpuCount'])} cores, CI=${String(data.environment['ci'])}, CPU ${String(data.environment['cpu'])}.`,
)
out.push('')
out.push(
  `**Control workload: ${data.controlWorkloadMs.toFixed(2)} ms.** Absolute timings below are meaningless on other hardware. ` +
    'Divide by this figure to compare against a run on a different machine.',
)
out.push('')
out.push(
  `Corpora carry an unloaded fraction of ${data.unloadedFraction}, so estimated spans are exercised throughout.`,
)
out.push('')

for (const scenario of scenarios) {
  const rows = data.measurements.filter((m) => m.scenario === scenario)
  if (rows.length === 0) continue
  out.push(`## ${scenario}`)
  out.push('')
  const batch = rows[0]?.batch ?? 1
  if (batch > 1) out.push(`Timed in batches of ${batch}; the per-operation column is derived.`)
  out.push('')
  out.push(`| shape | nodes | samples | p50 ms | p95 ms | p99 ms | max ms |`)
  out.push(`| --- | ---: | ---: | ---: | ---: | ---: | ---: |`)
  for (const shape of shapes) {
    for (const size of sizes) {
      const m = rows.find((r) => r.shape === shape && r.nodes === size)
      if (m === undefined) continue
      out.push(
        `| ${shape} | ${size.toLocaleString('en-US')} | ${m.samples} | ${fmt(m.p50Ms)} | ${fmt(m.p95Ms)} | ${fmt(m.p99Ms)} | ${fmt(m.maxMs)} |`,
      )
    }
  }
  out.push('')
}

out.push('## Retained heap')
out.push('')
out.push('| shape | nodes | rows | store | projection | ratio |')
out.push('| --- | ---: | ---: | ---: | ---: | ---: |')
for (const h of data.heaps) {
  out.push(
    `| ${h.shape} | ${h.nodes.toLocaleString('en-US')} | ${h.rows.toLocaleString('en-US')} | ${bytes(h.storeBytes)} | ${bytes(h.projectionBytes)} | ${h.ratio.toFixed(2)}x |`,
  )
}
out.push('')

writeFileSync('docs/benchmarks.md', `${out.join('\n')}\n`)
process.stdout.write(`wrote docs/benchmarks.md from ${chosen}\n`)
